name: Disable Pages Build

on:
  push:
    branches: [ main ]

jobs:
  disable-pages-build:
    runs-on: ubuntu-latest
    steps:
    - name: Disable Pages Build
      run: |
        echo "GitHub Pages build is handled by our custom workflow"
        echo "This prevents duplicate deployments" 